import type { Tutor } from "./index";

export const initialTutorData: Tutor[] = [
  {
    id: "T-001",
    nombre: "María",
    apellido: "González",
    email: "maria.gonzalez@ejemplo.com",
    telefono: "+1 234-567-8901",
    especialidadTecnica: "Redes y Comunicaciones",
    areaAsignada: "Producción",
    status: "active",
    fechaContratacion: "2024-01-15",
  },
  {
    id: "T-002",
    nombre: "Juan",
    apellido: "Rodríguez",
    email: "juan.rodriguez@ejemplo.com",
    telefono: "+1 234-567-8902",
    especialidadTecnica: "Electricidad Industrial",
    areaAsignada: "Mantenimiento",
    status: "active",
    fechaContratacion: "2024-02-20",
  },
  {
    id: "T-003",
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@ejemplo.com",
    telefono: "+1 234-567-8903",
    especialidadTecnica: "Mecánica Automotriz",
    areaAsignada: "Calidad",
    status: "pending",
    fechaContratacion: "2024-03-10",
  },
  {
    id: "T-004",
    nombre: "Carlos",
    apellido: "López",
    email: "carlos.lopez@ejemplo.com",
    telefono: "+1 234-567-8904",
    especialidadTecnica: "Instrumentación y Control",
    areaAsignada: "Seguridad Industrial",
    status: "pending",
    fechaContratacion: "2024-04-05",
  },
  {
    id: "T-005",
    nombre: "Laura",
    apellido: "Sánchez",
    email: "laura.sanchez@ejemplo.com",
    telefono: "+1 234-567-8905",
    especialidadTecnica: "Electrónica",
    areaAsignada: "Logística",
    status: "deleted",
    fechaContratacion: "2024-05-12",
    deletedAt: "2024-06-01",
  },
  {
    id: "T-006",
    nombre: "Roberto",
    apellido: "Díaz",
    email: "roberto.diaz@ejemplo.com",
    telefono: "+1 234-567-8906",
    especialidadTecnica: "Automatización Industrial",
    areaAsignada: "Ingeniería",
    status: "deleted",
    fechaContratacion: "2024-06-18",
    deletedAt: "2024-07-01",
  },
   
];
